name: Add Submodule

on:
  push:
    branches:
      - main

jobs:
  add-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add Submodule
      run: git submodule add https://github.com/krossovochkin/personal-website.git website

    - name: Commit Changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add submodule"
        git push
